name: OPENRLHF PyPi Nightly

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-and-publish:
    # do not run in forks
    if: ${{ github.repository_owner == 'OpenLLMAI' }}
    name: build wheel and upload
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Determine if commit was today
      id: commit_check
      run: |
        timestamp=$(git log -1 --format=%at)
        days=$(( ( $(date +%s) - timestamp ) / 86400 ))
        if [ $days -eq 0 ]; then
          echo "COMMIT_TODAY=true" >> $GITHUB_ENV
        else
          echo "COMMIT_TODAY=false" >> $GITHUB_ENV
        fi

    - name: Install dependencies
      if: env.COMMIT_TODAY == 'true'
      run: |
        pip install .

    - name: Build wheel
      if: env.COMMIT_TODAY == 'true'
      env:
        OPENRLHF_BUILD_MODE: nightly
      run: |
        python setup.py bdist_wheel

    - name: Upload to PyPi
      if: env.COMMIT_TODAY == 'true'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}